// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aspnetproject.Data;

#nullable disable

namespace aspnetproject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aspnetproject.Data.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CommenterUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommenterUserId");

                    b.HasIndex("PostId");

                    b.ToTable("Comments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CommentContent = "Alice comments on Bob's post.",
                            CommenterUserId = 2,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 31, 0, 0, DateTimeKind.Utc),
                            PostId = 2
                        },
                        new
                        {
                            Id = 2,
                            CommentContent = "Bob comments on his own post.",
                            CommenterUserId = 3,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 32, 0, 0, DateTimeKind.Utc),
                            PostId = 2
                        },
                        new
                        {
                            Id = 3,
                            CommentContent = "Charlie comments on Bob's post.",
                            CommenterUserId = 4,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 33, 0, 0, DateTimeKind.Utc),
                            PostId = 2
                        },
                        new
                        {
                            Id = 4,
                            CommentContent = "Bob comments on Alice's post.",
                            CommenterUserId = 3,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 34, 0, 0, DateTimeKind.Utc),
                            PostId = 1
                        },
                        new
                        {
                            Id = 5,
                            CommentContent = "Orphaned comment with no active author.",
                            CreatedAt = new DateTime(2026, 9, 6, 11, 35, 0, 0, DateTimeKind.Utc),
                            PostId = 1
                        });
                });

            modelBuilder.Entity("aspnetproject.Data.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddresseeUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("FriendshipStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("RequesterUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeUserId");

                    b.HasIndex("RequesterUserId", "AddresseeUserId")
                        .IsUnique();

                    b.ToTable("Friendships", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddresseeUserId = 3,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 20, 0, 0, DateTimeKind.Utc),
                            FriendshipStatus = "Accepted",
                            LastUpdatedAt = new DateTime(2026, 9, 6, 11, 21, 0, 0, DateTimeKind.Utc),
                            RequesterUserId = 2,
                            SentAt = new DateTime(2026, 9, 6, 11, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AddresseeUserId = 5,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 22, 0, 0, DateTimeKind.Utc),
                            FriendshipStatus = "Pending",
                            RequesterUserId = 2,
                            SentAt = new DateTime(2026, 9, 6, 11, 22, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AddresseeUserId = 2,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 23, 0, 0, DateTimeKind.Utc),
                            FriendshipStatus = "Pending",
                            RequesterUserId = 4,
                            SentAt = new DateTime(2026, 9, 6, 11, 23, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AddresseeUserId = 4,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 24, 0, 0, DateTimeKind.Utc),
                            FriendshipStatus = "Declined",
                            LastUpdatedAt = new DateTime(2026, 9, 6, 11, 25, 0, 0, DateTimeKind.Utc),
                            RequesterUserId = 3,
                            SentAt = new DateTime(2026, 9, 6, 11, 24, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("aspnetproject.Data.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AuthorizedRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("Succeeded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Logs", (string)null);
                });

            modelBuilder.Entity("aspnetproject.Data.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ReceiverUserId")
                        .HasColumnType("int");

                    b.Property<bool>("Seen")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SeenAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("SenderUserId", "ReceiverUserId", "CreatedAt");

                    b.ToTable("Messages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 36, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Old unread message from Bob to Alice.",
                            ReceiverUserId = 2,
                            Seen = false,
                            SenderUserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 38, 0, 0, DateTimeKind.Utc),
                            LastUpdatedAt = new DateTime(2026, 9, 6, 11, 39, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Read message from Alice to Bob.",
                            ReceiverUserId = 3,
                            Seen = true,
                            SeenAt = new DateTime(2026, 9, 6, 11, 39, 0, 0, DateTimeKind.Utc),
                            SenderUserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 40, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Latest message from Alice to Bob.",
                            ReceiverUserId = 3,
                            Seen = false,
                            SenderUserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 41, 0, 0, DateTimeKind.Utc),
                            MessageContent = "Latest unread message from Bob to Alice.",
                            ReceiverUserId = 2,
                            Seen = false,
                            SenderUserId = 3
                        });
                });

            modelBuilder.Entity("aspnetproject.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PostContent")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("PostTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 26, 0, 0, DateTimeKind.Utc),
                            PostContent = "Alice owns this post.",
                            PostTitle = "Alice Post",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 27, 0, 0, DateTimeKind.Utc),
                            PostContent = "Bob's post should appear in Alice's feed.",
                            PostTitle = "Bob Post",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 28, 0, 0, DateTimeKind.Utc),
                            PostContent = "Charlie's public post should not appear in Alice's friend feed.",
                            PostTitle = "Charlie Post",
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 29, 0, 0, DateTimeKind.Utc),
                            PostContent = "Post owned by a deactivated user.",
                            PostTitle = "Erin Deactivated Post",
                            UserId = 6
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 30, 0, 0, DateTimeKind.Utc),
                            PostContent = "Post owned by a soft-deleted user.",
                            PostTitle = "Frank Deleted Post",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("aspnetproject.Data.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 42, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 9, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            TokenHash = "ALICEactiveRefreshTokenHash000000000000000",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 9, 6, 11, 43, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 9, 13, 12, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2026, 9, 6, 11, 44, 0, 0, DateTimeKind.Utc),
                            TokenHash = "ALICErevokedRefreshTokenHash00000000000000",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 8, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            ExpiresAt = new DateTime(2026, 9, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            RevokedAt = new DateTime(2026, 9, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            TokenHash = "ALICEexpiredRefreshTokenHash00000000000000",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("aspnetproject.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 8, 31, 15, 4, 0, 0, DateTimeKind.Utc),
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 8, 31, 15, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("aspnetproject.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AccountDeactivatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("NULL");

                    b.Property<DateTime?>("AccountDeletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("NULL");

                    b.Property<string>("Bio")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastOnlineAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nchar(44)")
                        .IsFixedLength();

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("nchar(44)")
                        .IsFixedLength();

                    b.Property<DateTime?>("ResetTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetTokenHash")
                        .HasMaxLength(44)
                        .HasColumnType("nvarchar(44)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UsernameLastChangedAt")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_User_DateOfBirth", "DATEDIFF(year, DateOfBirth, GETUTCDATE()) BETWEEN 13 AND 100");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Admin",
                            CreatedAt = new DateTime(2026, 9, 6, 11, 4, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 8, 16, 2, 3, 9, 0, DateTimeKind.Utc),
                            Email = "benashvilisandro91@gmail.com",
                            PasswordHash = "x3UgoGJFZ2X3VJBAaQyF4J+M9+gfXP6vdO1W4jNwUzQ=",
                            PasswordSalt = "o0wzhm224CIRy46p73NmiqjhaEtU5pyOuZ60rUHOM+g=",
                            ResetTokenHash = "",
                            Username = "sandro_beno"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Primary test caller",
                            CreatedAt = new DateTime(2026, 9, 6, 10, 50, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            PasswordHash = "x3UgoGJFZ2X3VJBAaQyF4J+M9+gfXP6vdO1W4jNwUzQ=",
                            PasswordSalt = "o0wzhm224CIRy46p73NmiqjhaEtU5pyOuZ60rUHOM+g=",
                            ResetTokenHash = "",
                            Username = "alice"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Alice's accepted friend",
                            CreatedAt = new DateTime(2026, 9, 6, 10, 55, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@example.com",
                            PasswordHash = "x3UgoGJFZ2X3VJBAaQyF4J+M9+gfXP6vdO1W4jNwUzQ=",
                            PasswordSalt = "o0wzhm224CIRy46p73NmiqjhaEtU5pyOuZ60rUHOM+g=",
                            ResetTokenHash = "",
                            Username = "bob"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Unrelated active user",
                            CreatedAt = new DateTime(2026, 9, 6, 11, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "charlie@example.com",
                            PasswordHash = "x3UgoGJFZ2X3VJBAaQyF4J+M9+gfXP6vdO1W4jNwUzQ=",
                            PasswordSalt = "o0wzhm224CIRy46p73NmiqjhaEtU5pyOuZ60rUHOM+g=",
                            ResetTokenHash = "",
                            Username = "charlie"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Pending friendship user",
                            CreatedAt = new DateTime(2026, 9, 6, 11, 5, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "diana@example.com",
                            PasswordHash = "x3UgoGJFZ2X3VJBAaQyF4J+M9+gfXP6vdO1W4jNwUzQ=",
                            PasswordSalt = "o0wzhm224CIRy46p73NmiqjhaEtU5pyOuZ60rUHOM+g=",
                            ResetTokenHash = "",
                            Username = "diana"
                        },
                        new
                        {
                            Id = 6,
                            AccountDeactivatedAt = new DateTime(2026, 9, 6, 11, 50, 0, 0, DateTimeKind.Utc),
                            Bio = "Deactivated fixture user",
                            CreatedAt = new DateTime(2026, 9, 6, 11, 10, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "erin@example.com",
                            PasswordHash = "x3UgoGJFZ2X3VJBAaQyF4J+M9+gfXP6vdO1W4jNwUzQ=",
                            PasswordSalt = "o0wzhm224CIRy46p73NmiqjhaEtU5pyOuZ60rUHOM+g=",
                            ResetTokenExpiresAt = new DateTime(2026, 9, 7, 12, 0, 0, 0, DateTimeKind.Utc),
                            ResetTokenHash = "ERINactivationTokenHash000000000000000000",
                            Username = "erin_deactivated"
                        },
                        new
                        {
                            Id = 7,
                            AccountDeletedAt = new DateTime(2026, 8, 12, 12, 0, 0, 0, DateTimeKind.Utc),
                            Bio = "Soft-deleted fixture user",
                            CreatedAt = new DateTime(2026, 9, 6, 11, 15, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "frank@example.com",
                            PasswordHash = "x3UgoGJFZ2X3VJBAaQyF4J+M9+gfXP6vdO1W4jNwUzQ=",
                            PasswordSalt = "o0wzhm224CIRy46p73NmiqjhaEtU5pyOuZ60rUHOM+g=",
                            ResetTokenHash = "",
                            Username = "frank_deleted"
                        });
                });

            modelBuilder.Entity("aspnetproject.Data.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("aspnetproject.Data.Models.Comment", b =>
                {
                    b.HasOne("aspnetproject.Data.Models.User", "CommenterUser")
                        .WithMany()
                        .HasForeignKey("CommenterUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("aspnetproject.Data.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommenterUser");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("aspnetproject.Data.Models.Friendship", b =>
                {
                    b.HasOne("aspnetproject.Data.Models.User", "AddresseeUser")
                        .WithMany()
                        .HasForeignKey("AddresseeUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("aspnetproject.Data.Models.User", "RequesterUser")
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AddresseeUser");

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("aspnetproject.Data.Models.Log", b =>
                {
                    b.HasOne("aspnetproject.Data.Models.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("aspnetproject.Data.Models.Message", b =>
                {
                    b.HasOne("aspnetproject.Data.Models.User", "ReceiverUser")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("aspnetproject.Data.Models.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ReceiverUser");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("aspnetproject.Data.Models.Post", b =>
                {
                    b.HasOne("aspnetproject.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("aspnetproject.Data.Models.RefreshToken", b =>
                {
                    b.HasOne("aspnetproject.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("aspnetproject.Data.Models.UserRole", b =>
                {
                    b.HasOne("aspnetproject.Data.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("aspnetproject.Data.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("aspnetproject.Data.Models.Post", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("aspnetproject.Data.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("aspnetproject.Data.Models.User", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
